begin;
drop table if exists CLIENTERESERVA;
drop table if exists TELEFONELOJA;
drop table if exists RESERVA;
drop table if exists LOJA;
drop table if exists PESSOA;
drop table if exists ELETRICA;
drop table if exists CLASSICA;
drop table if exists BICICLETA;
drop table if exists DISPOSITIVO;
commit;